/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreatePacketArgs } from "./CreatePacketArgs";
import { UpdatePacketArgs } from "./UpdatePacketArgs";
import { DeletePacketArgs } from "./DeletePacketArgs";
import { PacketCountArgs } from "./PacketCountArgs";
import { PacketFindManyArgs } from "./PacketFindManyArgs";
import { PacketFindUniqueArgs } from "./PacketFindUniqueArgs";
import { Packet } from "./Packet";
import { PartFindManyArgs } from "../../part/base/PartFindManyArgs";
import { Part } from "../../part/base/Part";
import { PacketService } from "../packet.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Packet)
export class PacketResolverBase {
  constructor(
    protected readonly service: PacketService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Packet",
    action: "read",
    possession: "any",
  })
  async _packetsMeta(
    @graphql.Args() args: PacketCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Packet])
  @nestAccessControl.UseRoles({
    resource: "Packet",
    action: "read",
    possession: "any",
  })
  async packets(@graphql.Args() args: PacketFindManyArgs): Promise<Packet[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Packet, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Packet",
    action: "read",
    possession: "own",
  })
  async packet(
    @graphql.Args() args: PacketFindUniqueArgs
  ): Promise<Packet | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Packet)
  @nestAccessControl.UseRoles({
    resource: "Packet",
    action: "create",
    possession: "any",
  })
  async createPacket(@graphql.Args() args: CreatePacketArgs): Promise<Packet> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Packet)
  @nestAccessControl.UseRoles({
    resource: "Packet",
    action: "update",
    possession: "any",
  })
  async updatePacket(
    @graphql.Args() args: UpdatePacketArgs
  ): Promise<Packet | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Packet)
  @nestAccessControl.UseRoles({
    resource: "Packet",
    action: "delete",
    possession: "any",
  })
  async deletePacket(
    @graphql.Args() args: DeletePacketArgs
  ): Promise<Packet | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Part], { name: "parts" })
  @nestAccessControl.UseRoles({
    resource: "Part",
    action: "read",
    possession: "any",
  })
  async resolveFieldParts(
    @graphql.Parent() parent: Packet,
    @graphql.Args() args: PartFindManyArgs
  ): Promise<Part[]> {
    const results = await this.service.findParts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
